### ISSUE TITLE
不规则区域的坐标通过什么方式取到呢？

### ISSUE THREAD

**Issue by liaodongxiaoxiao** [dreamlivemeng/HotImg#1]
我大概看了一下源码，非常棒。
我想问一下这个区域坐标是通过什么方式取到的？
比方说我想获取demo中辽宁省的范围坐标点呢？

**Comment by dreamlivemeng** [comment]
通过图片像素点坐标。比如说一张图片像素800X600，在其坐上方（从左上方顶点开始）有一个50x50的正方形区域，那么他们pts为{0,0,0,50,50,50,50,0}也就是正方形的四个区域。那么对应demo的辽宁省市一个多边形的区域，就对应有多个坐标点。

**Comment by ppjuns** [comment]
怎么生成china.xml的@dreamlivemeng

**Comment by dreamlivemeng** [comment]
现在只能手动写，china.xml就是稍微获取其坐标麻烦一些。
